### PR TITLE
#199 Add md5 hash to s3 path prefix

### PR DESCRIPTION
**Pull request by pritamm**

### CODE REVIEW

**Comment by HenryCaiHaiying** [comment]
This md5Hash should be optional thing, please add a parameter to control this.

Also can you squash all the commits into one?

**Comment by pritamm** [comment]
Sure. Will do the necessary changes. Thanks.

**Comment by pritamm** [comment]
I made the changes for making it optional. Also tried squashing in the commits, could do that for first 3, then my eclipse setting was causing some imports to remove automatically and hence had to checkin few more commits. And now I am unable to squash them in.

**Comment by HenryCaiHaiying** [comment]
I will merge in the PR for now.  Thanks for the contribution.  The squash thing will be harder once you start to re-sync with the master, better to be done before the rebase.

**Comment by pritamm** [comment]
Thanks.

**Pull request merged**
