### PR TITLE
Updating Readme to match current Version in pom

### PR DESCRIPTION
**Pull request by damaex17**

### CODE REVIEW

**Comment by HenryCaiHaiying** [comment]
Thanks for the change.  I didn't realize we have hard-coded secor version string in README file.  Can you do one step further, instead of hard-code another version in README file (which might change again in the near future), can you just use some version token string (e.g. secor-<latest-version>) in README file?

**Comment by rud-bookbites** [comment]
Should probably be closed

**Comment by HenryCaiHaiying** [comment]
But the version string way passed 0.2, I think we should just ask people to check the version string in pom.xml and reference that version in the README

**Comment by rud-bookbites** [comment]
Yeah, this detail is in a bunch of places, a general "heads up" is probably more helpful

**Comment by HenryCaiHaiying** [comment]
@rud-bookbites do you want that information in README file?

**Comment by rud-bookbites** [comment]
There are multiple issues mentioning this problem. A bit of text in the readme would be helpful. Some more documentation would probably help even more, maybe in the form of guides or common use-cases. 

I suggested closing the issue as it is so old without activity is all.

**Comment by HenryCaiHaiying** [comment]
Closed since the change was already out of date with the current code.

**Pull request closed without merging**
