### PR TITLE
Kafka upgrade and use roundrobin assignment

### PR DESCRIPTION
**Pull request by yyejun**
Upgrade kafka to 0.8.2.1.
Use roundrobin assignment.

I also have to fix current zookeeper script, because 0.8.2.1 depends on new zookeeper version which seems not support command line.

### CODE REVIEW

**Comment by nguyenvanthan** [comment]
:+1:

**Comment by pgarbacki** [comment]
@yyejun could you squash your commits? Other than that, r+

**Comment by yyejun** [comment]
done.@pgarbacki what does r+ mean?

**Comment by pgarbacki** [comment]
@yyejun thanks. r+ means LGTM, or ready to land.

**Pull request merged**
