### PR TITLE
GCS daily and hourly folder structure support

### PR DESCRIPTION
**Pull request by ahsandar**
it allows to have folder structure for `GCS`  with date and hour partitions `Buckets/kafka-secor-backup/env/20161017/01/Logs/offset=0`

### CODE REVIEW

**Comment by HenryCaiHaiying** [comment]
There is already hourly/minutely partition support in secor, e.g. through partitioner.granularity.hour, can you use that feature?

**Comment by ahsandar** [comment]
@HenryCaiHaiying `partitioner.granularity.hour` enforces to write under hours and not to a dated folder if required and there was a PR opened related to having option to changing date format which wasn't merged because that could cause trouble with data import to Hive from S3 (can't find it right now).  so  it has a different functionality with felxibility for GCS uploads

**Comment by ahsandar** [comment]
here it is https://github.com/pinterest/secor/pull/74, indicating limitations due to HIVE

**Comment by HenryCaiHaiying** [comment]
When people use partitioner.granularity.hour for hourly partitioning, it's usually put in into the following folder structure:
   .../topc1/dt=2016-10-10/hr=01

And on hive table side, you define the hive table takes two partition column, e.g.:

create external table ... (
)
PARTITIONED BY ( 
  `dt` string, 
  `hr` string)

Is this what you want?  You can take a look at TimestampdMessageParser

Pawel didn't like customizing message parser class too much in the beginning, but we end up convincing him to support the hourly partition scheme.

**Comment by ahsandar** [comment]
I m looking for the flexibility to have different date and hour format and support to only write to a dated folder with no hourly partitioning,  is that possible currently in secor?

**Comment by HenryCaiHaiying** [comment]
The format in TimestampedMessageParser is currently hardcoded, you can
modify it to take in format config parameters.

I am not exactly sure what is a dated folder with no hourly partitioning
but still supporting hour format?

**Comment by ahsandar** [comment]
option to write to both type of buckets 
`Buckets/kafka-secor-backup/env/20161017/Logs/offset=0`
`Buckets/kafka-secor-backup/env/20161017/01/Logs/offset=0`,
 will check the `TimestampedMessageParser` and have  a PR for it if that is more suitable

**Comment by ahsandar** [comment]
from the looks of the code in `TimestampedMessageParser` it should always create a `dt=yyyy-MM-dd` partition, but I don't seem to be getting that, does enabling `secor.finalizer.lookback.periods=` initiates the partitions ?

**Comment by HenryCaiHaiying** [comment]
Are you using one of the subclasses of TimestampedMessageParser, e.g.
jsonMessageParser or ProtobufMessageParser?

**Comment by ahsandar** [comment]
This PR is outdated, alredy closed it as this was discarded, not sure what you mean by that

**Pull request closed without merging**
