### PR TITLE
fix Locale in DateMessageParser, fix Locale dependency

### PR DESCRIPTION
**Pull request by nguyenvanthan**
Fix Locale in DateMessageParser.
The Locale should be set in a config file or unit test should not be local dependent.

Should fix https://github.com/pinterest/secor/issues/78

### CODE REVIEW

**Comment by HenryCaiHaiying** [comment]
Will this break the program if people are running secor in Europe?

**Comment by nguyenvanthan** [comment]
It depends if you use number representation or letter representation in your date pattern.
Example: ```dd-MM-yyyy``` will be fine but if you use  ```dd MMMMM yyyy``` it will expect the month as a word based on a Locale.
Maybe you should ask users to use only digits in date pattern.

**Comment by HenryCaiHaiying** [comment]
How about you make this defaultLocal (and also defaultFormatter) a configuration parameter coming through secor.common.properties?

**Comment by nguyenvanthan** [comment]
Maybe i can add ```message.timestamp.input.pattern.locale.language```, default to "en" and where language is "an ISO 639 alpha-2 or alpha-3 language code, or a language subtag up to 8 characters in length" ?

**Comment by HenryCaiHaiying** [comment]
This seems quite complicated.  I think as long as you allow people specify their own 'defaultLocale'/defaultFormatter, that should be fine.

**Comment by HenryCaiHaiying** [comment]
This PR would need to sync with the latest code.

**Pull request closed without merging**
