### PR TITLE
Fix issues with FileReaderWriterFactoryTest

### PR DESCRIPTION
**Pull request by jonathan-stein**
Fix issue with powermock mocking FileSystem as mentioned in #1686

### CODE REVIEW

**Comment by HenryCaiHaiying** [comment]
Thanks for the fix, I think you can also remove the deprecated powermock code.

**Comment by HenryCaiHaiying** [comment]
The build is clean now.

**Comment by jonathan-stein** [comment]
I have removed the commented powermock code

**Comment by HenryCaiHaiying** [comment]
Looks good to me, I will merge it in.  Thanks for the contribution.

**Pull request merged**
